### PR TITLE
Automaticly detect serial or network connection

### PR DESCRIPTION
**Pull request by dawonn**
I added the default IP address to the param

the node first tries connecting via the serial port, if it fails it tries the network. If both fail it spews out the error messages from the connection attempts.

Tested with an UTM-30LX-EW (Ethernet)

### CODE REVIEW

**Comment by chadrockey** [comment]
This would break the case where a serial device was connected to the same computer that a network device was to be accessed.

**Comment by dawonn** [comment]
Not necessarily, if you happen to have both connected to the same computer,
you could specify the serial port param = null and it would always fail to
connect to the serial port and then try to connect via ethernet. Works both
ways actually, you can set the IP param to null and it will never be able
to connect to anything except serial port.

If you wish to increase clarity, perhaps I could add a disable-network
and/or disable-serial param.

Btw, thanks for this package, its just what the doctor ordered. :-)

~Dereck

**Comment by chadrockey** [comment]
That's exactly how it works now, but it defaults to serial Hokuyos.  ;)  IP address is default to the null string.  Why try to open something and fail?

It is eventually intended to be a drop in replacement for hokuyo_node.  For that reason, if you don't specify ip_address, then it should default to a serial device.

**Comment by dawonn** [comment]
Why? Because in the default case where there is only one hokuyo connected
to the system, it "just works" regardless of the connection method.  Zero
config! :D

For users that wish to use it as a drop in replacement for the hokuyo_node,
this change should not effect them either, it will still default to the
serial port. If there is a hokuyo attached there.

**Comment by tfoote** [comment]
I'd avoid adding the extra logic into the driver, it's very opaque and hard
to debug by the user.  With this proposal it will "just work" if there's
one default configured network hokuyo.  But if you then plug in a serial
hokuyo it will "just work" differently.  Having a default connection is
fine, changing the default behavior needs to be reviewed to make sure it's
not going to break anyone who is relying on these features.  And having
default behavior which is configuration dependent will make avoiding
breaking anyone much harder in the future.

**Comment by jack-oquin** [comment]
I agree with Tully and Chad. 

The additional convenience is not worth making things hard for users to understand. They already know how to set the correct parameter.

**Comment by t1jump** [comment]
Found this thread and want to verify... is the urg_node a replacement for the hokuyo_node and all versions of Hokuyo (URG, UTM, etc.)?

**Comment by chadrockey** [comment]
This node works with more hokuyos than hokuyo_node, but its not currently a
direct replacement.  I do recommend it for new users and new robots.

Hokuyo_node will be supported until this node is mature and until PR2 can
switch over.

This is also not a great place to ask this question.  Please see the
support guidelines:
http://www.ros.org/wiki/Support

Found this thread and want to verify... is the urg_node a replacement for
the hokuyo_node and all versions of Hokuyo (URG, UTM, etc.)?

—
Reply to this email directly or view it on
GitHubhttps://github.com/ros-drivers/urg_node/pull/1#issuecomment-18685322
.

**Pull request closed without merging**
