### PR TITLE
install getID

### LINKED ISSUE #9: getID is not created
I've installed the urg_node package using apt-get and manually, and in either case it seems as though getID.cpp is not compiled into an executable.  I am running ROS Hydro in Ubuntu 12.04LTS.

Thanks!

### PR DESCRIPTION
**Pull request by k-okada**
fixed https://github.com/ros-drivers/urg_node/issues/9

### CODE REVIEW

**Comment by NikolausDemmel** [comment]
+1
I just stumbled on this, since the wiki page mentions the existance of getID in the example udev rule. Any chance of getting this in some time?

**Comment by kmhallen** [comment]
Any chance we can merge this?

**Comment by davide-tateo90** [comment]
still missing ros-kinetic-urg-node/xenial,now 0.1.9-0xenial-20161026-203817-0700 amd64

**Comment by kmhallen** [comment]
@chadrockey Any chance we can merge this?

**Comment by tonybaltovski** [comment]
Thanks @k-okada

**Pull request merged**
